const state={page:'overview',user:null,date:null,users:[],overview:null,metering:null,meteringHistory:[],equipment:null,waveform:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const colors={cyan:'#13d7d1',blue:'#328bf3',amber:'#f1aa34',red:'#ff5d58',green:'#38d39f',grid:'#203445',text:'#78909e'};
const stageColors={H0:'#38d39f',H1:'#72d582',H2:'#f1c54a',H3:'#f18b3c',H4:'#ff5d58'};
const riskColors={严重:'#ff394f',高:'#ff6c4a',中:'#f1aa34',较低:'#54bdda'};
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){let d;try{d=await r.json()}catch{}throw new Error(d?.detail||`${r.status} ${r.statusText}`)}return r.json()}
function notice(t=''){const e=$('#notice');e.textContent=t;e.classList.toggle('hidden',!t)}
function fmt(v,d=2){return v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d)}
function kpis(e,a){e.innerHTML=a.map(x=>`<div class="kpi" style="--accent:${x.color||colors.cyan}"><label>${x.label}</label><strong>${x.value}</strong><small>${x.note||''}</small></div>`).join('')}
function bars(e,a,max=100){e.innerHTML=a.map(x=>`<div class="bar-row"><label title="${x.label}">${x.label}</label><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,Number(x.value)/Math.max(max,1)*100))}%;background:${x.color||''}"></div></div><output>${x.display??fmt(x.value,1)}</output></div>`).join('')}
function canvas(c){const d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(300,r.width*d);c.height=(+c.getAttribute('height')||220)*d;const x=c.getContext('2d');x.scale(d,d);return{x,w:c.width/d,h:c.height/d}}
function lineChart(c,s,o={}){const{x,w,h}=canvas(c),p={l:46,r:18,t:20,b:30},iw=w-p.l-p.r,ih=h-p.t-p.b,a=s.flatMap(z=>z.values).filter(Number.isFinite),mn=o.min??Math.min(...a,0),mx=o.max??Math.max(...a,1);x.strokeStyle=colors.grid;x.fillStyle=colors.text;x.font='10px Consolas';for(let i=0;i<=4;i++){let y=p.t+ih*i/4;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillText((mx-(mx-mn)*i/4).toFixed(o.decimals??0),5,y+3)}s.forEach(z=>{x.strokeStyle=z.color;x.lineWidth=z.width||2;x.beginPath();z.values.forEach((v,i)=>{let px=p.l+iw*i/Math.max(1,z.values.length-1),py=p.t+ih*(1-(v-mn)/(mx-mn||1));i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()});(o.labels||[]).forEach((l,i,a)=>{if(i%Math.ceil(a.length/6)===0)x.fillText(l.slice(5),p.l+iw*i/Math.max(1,a.length-1)-16,h-8)});let lx=p.l;s.forEach(z=>{x.fillStyle=z.color;x.fillRect(lx,3,12,3);x.fillStyle='#9bb0bb';x.fillText(z.name,lx+17,8);lx+=x.measureText(z.name).width+42})}
function barChart(c,a){const{x,w,h}=canvas(c),p=38,g=18,m=Math.max(...a.map(z=>z.value),1),bw=(w-p*2-g*(a.length-1))/a.length;x.strokeStyle=colors.grid;x.beginPath();x.moveTo(p,h-28);x.lineTo(w-p,h-28);x.stroke();a.forEach((z,i)=>{let bh=(h-70)*z.value/m,px=p+i*(bw+g),py=h-28-bh,gr=x.createLinearGradient(0,py,0,h);gr.addColorStop(0,z.color);gr.addColorStop(1,'rgba(19,215,209,.1)');x.fillStyle=gr;x.fillRect(px,py,bw,bh);x.fillStyle='#9cb0ba';x.font='10px Consolas';x.textAlign='center';x.fillText(z.label,px+bw/2,h-10);x.fillText(fmt(z.value,0),px+bw/2,py-7)});x.textAlign='left'}

async function init(){try{const d=await api('/api/users'),dateSelect=$('#dateSelect');state.users=d.items||[];$('#userSelect').innerHTML=state.users.map(u=>`<option value="${u.user_id}">${u.company_name} · ${u.user_id}</option>`).join('');const[start,end]=d.date_range||[],dates=[];if(!start||!end)throw new Error('接口未返回可用检测日期');for(let x=new Date(start+'T00:00:00');x<=new Date(end+'T00:00:00');x.setDate(x.getDate()+1))dates.push(new Date(x).toISOString().slice(0,10));if(!dates.length)throw new Error('检测日期范围无效');dateSelect.innerHTML=dates.map(x=>`<option value="${x}">${x}</option>`).join('');state.user=$('#userSelect').value||null;state.date=dates.includes(end)?end:dates.at(-1);dateSelect.value=state.date;await loadOverview()}catch(e){notice('初始化失败：'+e.message)}}
async function refresh(){if($('#userSelect').value)state.user=$('#userSelect').value;const dateSelect=$('#dateSelect'),fallbackDate=state.date||dateSelect.options[dateSelect.options.length-1]?.value;state.date=dateSelect.value||fallbackDate;if(!state.date){notice('诊断失败：请选择有效的检测日期');return}dateSelect.value=state.date;notice();const b=$('#refreshButton');b.disabled=true;b.textContent=state.page==='overview'?'正在诊断715家企业…':'正在读取详情…';try{if(state.page==='overview')await loadOverview();else if(state.page==='metering')await loadMetering();else await loadEquipment()}catch(e){notice('诊断失败：'+e.message)}finally{b.disabled=false;b.textContent=state.page==='overview'?'执行每日全量诊断':'刷新当前企业详情'}}

async function loadOverview(){if(!state.date)throw new Error('请选择有效的检测日期');state.overview=await api(`/daily/overview/${encodeURIComponent(state.date)}`);renderOverview(state.overview);$('#overviewStatus').textContent=`${state.date} · 已完成`;$('#overviewStatus').classList.add('ok')}
function renderOverview(d){kpis($('#overviewKpis'),[
 {label:'已自动诊断企业',value:d.diagnosed_enterprises,note:'当天全量用户',color:colors.cyan},
 {label:'异常企业',value:d.abnormal_enterprises,note:`正常企业 ${d.normal_enterprises}`,color:colors.amber},
 {label:'计量问题事件',value:d.metering_issue_count,note:'用气、量程与数据质量',color:colors.blue},
 {label:'设备问题事件',value:d.equipment_issue_count,note:`高/严重问题 ${d.severe_count}`,color:colors.red}
 ]);barChart($('#moduleChart'),[{label:'智能计量',value:d.metering_issue_count,color:colors.blue},{label:'智能设备',value:d.equipment_issue_count,color:colors.amber}]);const rc={严重:0,高:0,中:0,较低:0};d.issues.forEach(x=>rc[x.risk_level]=(rc[x.risk_level]||0)+1);bars($('#riskDistribution'),Object.entries(rc).map(([k,v])=>({label:k,value:v,color:riskColors[k]})),Math.max(...Object.values(rc),1));const tc={};d.issues.forEach(x=>tc[x.issue_type]=(tc[x.issue_type]||0)+1);const top=Object.entries(tc).sort((a,b)=>b[1]-a[1]).slice(0,6);bars($('#issueTypeRanking'),top.map(([k,v])=>({label:k,value:v,color:colors.cyan})),Math.max(...top.map(x=>x[1]),1));renderIssueTable()}
function renderIssueTable(){if(!state.overview)return;const q=$('#issueSearch').value.trim().toLowerCase(),m=$('#moduleFilter').value,r=$('#riskFilter').value;const rows=state.overview.issues.filter(x=>(m==='all'||x.module===m)&&(r==='all'||x.risk_level===r)&&(!q||`${x.company_name} ${x.user_id} ${x.issue_tags.join(' ')}`.toLowerCase().includes(q)));$('#issueTable').innerHTML=rows.length?rows.map((x,i)=>`<tr class="issue-row" data-index="${state.overview.issues.indexOf(x)}"><td><span class="risk-dot" style="background:${riskColors[x.risk_level]}"></span>${x.risk_level}</td><td><b>${x.company_name}</b><br><small>${x.user_id}</small></td><td><span class="module-badge">${x.module==='metering'?'智能计量':'智能设备'}</span></td><td>${x.issue_tags.join('、')}</td><td>${x.evidence_summary}</td><td>${x.primary_metric_name}：${fmt(x.primary_metric)}${x.primary_metric_name.includes('偏差')?'%':''}</td><td><span class="view-link">查看证据 →</span></td></tr>`).join(''):'<tr><td colspan="7">没有符合筛选条件的问题企业</td></tr>';$$('.issue-row').forEach(row=>row.addEventListener('click',()=>openIssue(state.overview.issues[+row.dataset.index]))) }
async function openIssue(issue){state.user=issue.user_id;if(![...$('#userSelect').options].some(x=>x.value===issue.user_id))$('#userSelect').add(new Option(`${issue.company_name} · ${issue.user_id}`,issue.user_id));$('#userSelect').value=issue.user_id;switchPage(issue.module);await refresh()}
function switchPage(page){state.page=page;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.page').forEach(x=>x.classList.remove('active'));$(`#${page}Page`).classList.add('active');document.body.classList.toggle('detail-view',page!=='overview');$('#refreshButton').textContent=page==='overview'?'执行每日全量诊断':'刷新当前企业详情'}

function decodeRisk(v,s){if(v&&!String(v).includes('�')&&!/[?]/.test(v))return v;return s>=80?'严重':s>=60?'高':s>=35?'中':'低'}
function decodeSpec(v,m){if(v&&!String(v).includes('�')&&!/[?]/.test(v))return v;if(!m?.qmax)return'量程信息不足';let a=m.small_flow_percentage||0,b=m.normal_flow_percentage||0,c=m.over_flow_percentage||0;return a-b>10?'表具选型偏大':c-b>10?'表具选型偏小':'表具选型正常'}
function normalizeMetering(d){let m=d.details?.meter_spec||{};return{...d,risk_level:decodeRisk(d.risk_level,d.risk_score),meter_spec_result:decodeSpec(d.meter_spec_result,m),summary:`风险评分 ${fmt(d.risk_score,0)}，估算补气量 ${fmt(d.makeup_volume)} m³，表具量程判定：${decodeSpec(d.meter_spec_result,m)}。`,alerts:d.alerts||[]}}
async function loadMetering(){const[d,h,s]=await Promise.all([api('/metering/diagnose',{method:'POST',body:JSON.stringify({user_id:state.user,diagnosis_date:state.date,save:false})}),api(`/daily/metering-history/${encodeURIComponent(state.user)}/${state.date}?days=7`),api(`/metering/signals/${encodeURIComponent(state.user)}/${state.date}`)]);state.metering=normalizeMetering(d);state.meteringHistory=h.items;state.meteringSignals=s;renderMetering(state.metering,h.items);renderMeteringMechanism(state.metering);renderMeteringSignals(s,state.metering);requestMeteringExplanation(state.metering);$('#meteringStatus').textContent='当天诊断 + 近7日证据';$('#meteringStatus').classList.add('ok')}
function renderMeteringMechanism(d){const observed=Number(d.observed_volume||0),expected=Number(d.predicted_normal_volume||0),drop=expected>0?Math.max(0,(expected-observed)/expected*100):0,intervals=d.anomaly_intervals||[],m=d.details?.meter_spec||{},isUnmetered=d.model_gas_state===1&&d.observed_gas_state===0;let mechanism=isUnmetered?'模型识别到设备处于用气状态，但远传瞬时流量未形成计量，符合“走气未走字”的交叉验证条件。':`远传数据仍记录到用气，但当日累计量显著低于该用户相同时段历史基线，属于“低于正常用气基线”异常，并非直接等同于走气未走字。`;let causes=isUnmetered?'可能涉及流量计卡滞、脉冲/远传故障、旁路计量或通信冻结。':'可能由企业真实停产/减产、阀门关闭、部分管路缺数、运行计划变化或流量计低计引起；需要现场业务信息排除正常工况变化。';$('#meteringMechanism').innerHTML=`<div class="mechanism-summary"><b>核心结论：</b>${mechanism}</div><div class="mechanism-grid"><div class="mechanism-step"><em>01 · 基线差异</em><b><span class="evidence-value">${fmt(observed)}</span> / ${fmt(expected)} m³</b><p>当日观测量较预测正常量低 ${fmt(drop,1)}%。正常量由历史同一5分钟时刻的中位数基线得到。</p></div><div class="mechanism-step"><em>02 · 区间判据</em><b>${intervals.length} 个连续异常区间</b><p>每个时刻只有在“期望流量－观测流量”超过 max(3×MAD，最小绝对阈值)，并连续至少2个采样点时才形成异常区间。</p></div><div class="mechanism-step"><em>03 · 损失量化</em><b><span class="evidence-value">${fmt(d.baseline_missing_volume)}</span> m³</b><p>对异常区间内的正偏差按5分钟步长积分，得到基线缺失量；表误差修正为 ${fmt(d.meter_bias_volume)} m³。</p></div><div class="mechanism-step"><em>04 · 风险与量程</em><b>${d.risk_level}风险 · ${d.meter_spec_result}</b><p>风险分 ${fmt(d.risk_score,0)}；小流量区占 ${fmt(m.small_flow_percentage||0,1)}%，正常量程占 ${fmt(m.normal_flow_percentage||0,1)}%，超量程占 ${fmt(m.over_flow_percentage||0,1)}%。</p></div></div><div class="mechanism-caution"><b>可能机理：</b>${causes}<br><b>现场核查顺序：</b>先确认当天是否停产/减产及阀门状态，再核对机械字轮与远传累计量，最后检查流量传感器、脉冲采集和通信链路。未排除真实工况变化前，“估算补气量”只能作为核查参考，不能直接认定为计量损失。</div>`}
function renderMetering(d,h){kpis($('#meteringKpis'),[{label:'当日观测用气量',value:fmt(d.observed_volume),note:'SCADA流量积分 · m³'},{label:'预测正常用气量',value:fmt(d.predicted_normal_volume),note:`历史基线 ${d.details?.baseline?.history_days||0} 天`,color:colors.blue},{label:'估算补气量',value:fmt(d.makeup_volume),note:`区间偏差 ${fmt(d.baseline_missing_volume)} + 表误差 ${fmt(d.meter_bias_volume)}`,color:colors.amber},{label:'风险等级',value:d.risk_level,note:`风险评分 ${fmt(d.risk_score,0)} / 100`,color:d.risk_score>=60?colors.red:d.risk_score>=35?colors.amber:colors.green}]);lineChart($('#volumeChart'),[{name:'日用气量',values:h.map(x=>x.volume),color:colors.cyan,width:2.5},{name:'最大流量',values:h.map(x=>x.max_flow),color:colors.amber,width:1.5}],{labels:h.map(x=>x.date),min:0});const g=$('#riskGauge');g.style.setProperty('--score',d.risk_score);g.style.setProperty('--gauge-color',d.risk_score>=60?colors.red:d.risk_score>=35?colors.amber:colors.green);g.innerHTML=`<div class="gauge-value"><b>${fmt(d.risk_score,0)}</b><small>${d.risk_level}风险</small></div>`;$('#riskFactors').innerHTML=[`异常区间 ${d.anomaly_intervals.length}`,`告警 ${d.alerts.length}`,d.meter_spec_result,`近7日 ${h.length} 天`].map(x=>`<span class="factor">${x}</span>`).join('');let m=d.details?.meter_spec||{};bars($('#meterRangeBars'),[{label:'小流量区',value:m.small_flow_percentage||0,color:colors.blue},{label:'正常量程',value:m.normal_flow_percentage||0,color:colors.green},{label:'超量程区',value:m.over_flow_percentage||0,color:colors.red}]);let q=d.details?.data_quality?.pipeline_completeness||{};bars($('#qualityBars'),Object.entries(q).map(([k,v])=>({label:`管路 ${k}`,value:(v||0)*100,color:(v||0)>.9?colors.green:colors.amber})));$('#intervalTable').innerHTML=d.anomaly_intervals.length?d.anomaly_intervals.map(x=>`<tr><td>${String(x.start_time).replace('T',' ').slice(0,16)}</td><td>${String(x.end_time).replace('T',' ').slice(0,16)}</td><td>${x.anomaly_type||'计量偏差'}</td><td>${fmt(x.observed_value)}</td><td>${fmt(x.expected_value)}</td><td>${fmt(x.estimated_missing_volume)} m³</td><td>${x.severity||'—'}</td></tr>`).join(''):'<tr><td colspan="7">当天未定位到连续异常区间</td></tr>'}

async function loadEquipment(){const[d,w]=await Promise.all([api(`/equipment/dashboard/${encodeURIComponent(state.user)}/${state.date}`),api(`/equipment/waveform/${encodeURIComponent(state.user)}/${state.date}`)]);state.equipment=d;state.waveform=w;renderEquipment(d,w);renderEquipmentMechanism();requestEquipmentExplanation(d);$('#equipmentStatus').textContent='当天诊断 + 近7日证据';$('#equipmentStatus').classList.add('ok')}
function renderEquipment(d,w){const c=d.current_assessment,t=d.trend_assessment,e=d.model_explanation,h=d.daily_history.filter(x=>x.date<=state.date).slice(-7);kpis($('#equipmentKpis'),[{label:'健康阶段',value:c.stage,note:c.stage_name,color:stageColors[c.stage]},{label:'健康指数',value:fmt(c.health_index),note:'连续健康度 · HI / 100',color:c.health_index<50?colors.red:colors.green},{label:'模型置信度',value:fmt(c.confidence*100,1)+'%',note:'五阶段最大后验概率',color:colors.blue},{label:'演化趋势',value:t.trend_name,note:`斜率 ${fmt(t.daily_slope,2)} 点/日`,color:t.daily_slope<-.35?colors.amber:colors.green}]);lineChart($('#healthChart'),[{name:'健康指数',values:h.map(x=>x.stabilized_health_index),color:colors.cyan,width:2.5},{name:'原始模型',values:h.map(x=>x.predicted_health_index),color:'#526e81',width:1}],{labels:h.map(x=>x.date),min:0,max:100});bars($('#stageProbabilities'),Object.entries(c.probabilities).map(([k,v])=>({label:`${k} ${['健康','轻衰减','衰减','重衰减','故障'][+k.slice(1)]}`,value:v*100,color:stageColors[k],display:fmt(v*100,1)+'%'})));lineChart($('#waveformChart'),[{name:'X轴',values:w.x,color:colors.cyan,width:1},{name:'Y轴',values:w.y,color:colors.amber,width:1},{name:'Z轴',values:w.z,color:'#a078ff',width:1}],{decimals:2});bars($('#axisWeights'),['X','Y','Z'].map((x,i)=>({label:x+'轴',value:(e.axis_weights[i]||0)*100,color:[colors.cyan,colors.amber,'#a078ff'][i]})));bars($('#scaleWeights'),e.scale_kernel_sizes.map((x,i)=>({label:`k=${x}`,value:(e.morphological_scale_weights[i]||0)*100,color:colors.blue})));$('#stageTimeline').innerHTML=(t.stage_sequence||[]).map((s,i)=>`<div class="timeline-item" style="--stage:${stageColors[s]}"><b>${s}</b><small>${i?'状态迁移':'起始状态'}</small></div>`).join('')+`<div class="timeline-item" style="--stage:${colors.cyan}"><b>${t.trend_name}</b><small>最大单日下降 ${fmt(t.maximum_daily_drop,1)}</small></div>`;$('#healthTable').innerHTML=h.map(x=>`<tr><td>${x.date}</td><td><span class="stage-badge" style="color:${stageColors[x.temporal_stage]}">${x.temporal_stage}</span></td><td>${fmt(x.stabilized_health_index)}</td><td>${fmt(x.confidence*100,1)}%</td><td>${x.operating_condition} m³/h</td><td>${x.predicted_stage} / ${fmt(x.predicted_health_index)}</td></tr>`).join('')}

function reportHtml(r){return `<div class="report-head"><div><p class="eyebrow">AGENT INSPECTION REPORT</p><h3>智能检查结果</h3></div><span>${r.report_id}</span></div><div class="report-summary">${r.inspection_conclusion}</div><span class="decision">${r.risk_level} · ${r.decision}</span><div class="report-columns"><div><h4>判定证据链</h4><ul>${r.evidence_chain.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><h4>现场检查清单</h4><ul>${r.checklist.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><h4>工单与处置建议</h4><p>${r.work_order_advice}</p><small style="display:block;color:#627e8b;margin-top:12px">${r.data_boundary} · ${r.generator}</small>`}
async function runAgent(m,b){const c=m==='metering'?state.metering:state.equipment;if(!c){notice('请先读取该企业详情');return}b.disabled=true;b.textContent='Agent分析中…';try{let r=await api('/agent/inspect',{method:'POST',body:JSON.stringify({module:m,user_id:state.user,diagnosis_date:state.date,field_text:$(`#${m}Text`).value,context:c})});$(`#${m}Report`).innerHTML=reportHtml(r)}catch(e){notice('Agent生成失败：'+e.message)}finally{b.disabled=false;b.textContent='生成智能检查结果'}}

$$('.nav-item').forEach(b=>b.addEventListener('click',async()=>{switchPage(b.dataset.page);await refresh()}));$('#refreshButton').addEventListener('click',refresh);$('#dateSelect').addEventListener('change',()=>{state.date=$('#dateSelect').value;refresh()});$('#userSelect').addEventListener('change',()=>{if(state.page!=='overview')refresh()});['issueSearch','moduleFilter','riskFilter'].forEach(id=>$('#'+id).addEventListener(id==='issueSearch'?'input':'change',renderIssueTable));$$('.agent-button').forEach(b=>b.addEventListener('click',()=>runAgent(b.dataset.module,b)));window.addEventListener('resize',()=>{if(state.page==='overview'&&state.overview)renderOverview(state.overview);if(state.page==='metering'&&state.metering)renderMetering(state.metering,state.meteringHistory);if(state.page==='equipment'&&state.equipment)renderEquipment(state.equipment,state.waveform)});init();
